<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>third-platform</artifactId>
        <groupId>com.cosmo.hhim.thirdplat</groupId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>
    <modules>
        <module>thirdplat-api-unipush</module>
        <module>im-api-operation</module>
        <module>thirdplat-api-wechatmp</module>
        <module>thirdplat-api-cosmosupport</module>
        <module>thirdplat-api-thirdclient</module>
        <module>thirdplat-api-wechatminiapp</module>
    </modules>

    <artifactId>thirdplat-api</artifactId>
    <packaging>pom</packaging>

</project>
